export const sourceCatalog = [
  {
    id: 'gov-cn',
    market: '中国',
    type: '官方发布',
    credibility: '高',
    name: '中国政府网',
    url: 'https://www.gov.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '通用航空', '空域', '适航'],
    cadenceHours: 12,
  },
  {
    id: 'caac',
    market: '中国',
    type: '官方发布',
    credibility: '高',
    name: '中国民用航空局',
    url: 'https://www.caac.gov.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '通用航空', '适航', '空域'],
    cadenceHours: 12,
  },
  {
    id: 'miit',
    market: '中国',
    type: '官方发布',
    credibility: '高',
    name: '工业和信息化部',
    url: 'https://www.miit.gov.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '航空装备', '电动垂直起降', '通用航空'],
    cadenceHours: 24,
  },
  {
    id: 'local-gov',
    market: '中国',
    type: '地方政府',
    credibility: '高',
    name: '地方政府与发改委公开信息',
    url: 'https://www.gov.cn/fuwu/dfbm.htm',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '产业园', '试点', '空域', '起降点'],
    cadenceHours: 24,
  },
  {
    id: 'faa',
    market: '美国',
    type: '官方发布',
    credibility: '高',
    name: '美国联邦航空管理局',
    url: 'https://www.faa.gov/AAM',
    crawlMode: 'watch-page',
    keywords: ['Advanced Air Mobility', 'electric vertical takeoff', 'vertiport', 'unmanned aircraft'],
    cadenceHours: 12,
  },
  {
    id: 'nasa',
    market: '美国',
    type: '官方发布',
    credibility: '高',
    name: '美国国家航空航天局',
    url: 'https://www.nasa.gov/mission/advanced-air-mobility/',
    feed: 'https://www.nasa.gov/rss/dyn/breaking_news.rss',
    crawlMode: 'rss',
    keywords: ['Advanced Air Mobility', 'drone', 'airspace', 'aviation'],
    cadenceHours: 12,
  },
  {
    id: 'dot',
    market: '美国',
    type: '官方发布',
    credibility: '高',
    name: '美国交通部',
    url: 'https://www.transportation.gov/',
    crawlMode: 'watch-page',
    keywords: ['Advanced Air Mobility', 'aviation', 'drone', 'infrastructure'],
    cadenceHours: 24,
  },
  {
    id: 'easa',
    market: '欧洲',
    type: '官方发布',
    credibility: '高',
    name: '欧洲航空安全局',
    url: 'https://www.easa.europa.eu/en/domains/drones-air-mobility/topics/urban-air-mobility-uam',
    crawlMode: 'watch-page',
    keywords: ['Urban Air Mobility', 'U-space', 'drone', 'electric vertical takeoff'],
    cadenceHours: 24,
  },
  {
    id: 'joby-ir',
    market: '美国',
    type: '企业公告',
    credibility: '高',
    name: 'Joby Aviation 投资者关系',
    url: 'https://ir.jobyaviation.com/',
    crawlMode: 'watch-page',
    keywords: ['certification', 'aircraft', 'delivery', 'commercial'],
    cadenceHours: 24,
  },
  {
    id: 'archer-ir',
    market: '美国',
    type: '企业公告',
    credibility: '高',
    name: 'Archer Aviation 投资者关系',
    url: 'https://investors.archer.com/',
    crawlMode: 'watch-page',
    keywords: ['aircraft', 'certification', 'manufacturing', 'order'],
    cadenceHours: 24,
  },
  {
    id: 'ehang-ir',
    market: '中国',
    type: '企业公告',
    credibility: '高',
    name: '亿航智能投资者关系',
    url: 'https://ir.ehang.com/',
    crawlMode: 'watch-page',
    keywords: ['适航', '商业运营', '订单', '无人驾驶航空器'],
    cadenceHours: 24,
  },
  {
    id: 'autoflight',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '峰飞航空',
    url: 'https://www.autoflight.com/',
    crawlMode: 'watch-page',
    keywords: ['峰飞', '凯瑞鸥', '盛世龙', '电动垂直起降', '适航', '货运', '订单'],
    cadenceHours: 24,
  },
  {
    id: 'aeroht',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '小鹏汇天',
    url: 'https://www.aeroht.com/',
    crawlMode: 'watch-page',
    keywords: ['小鹏汇天', '飞行汽车', '陆地航母', '低空出行', '量产', '预售'],
    cadenceHours: 24,
  },
  {
    id: 'aerofugia',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '沃飞长空',
    url: 'https://www.aerofugia.com/',
    crawlMode: 'watch-page',
    keywords: ['沃飞长空', 'AE200', '电动垂直起降', '适航', '低空出行'],
    cadenceHours: 24,
  },
  {
    id: 'volant',
    market: '中国',
    type: '企业公告',
    credibility: '中',
    name: '沃兰特',
    url: 'https://www.volantaero.com/',
    crawlMode: 'watch-page',
    keywords: ['沃兰特', 'VE25', '电动垂直起降', '适航', '融资'],
    cadenceHours: 24,
  },
  {
    id: 'tcab',
    market: '中国',
    type: '企业公告',
    credibility: '中',
    name: '时的科技',
    url: 'https://www.tcabtech.com/',
    crawlMode: 'watch-page',
    keywords: ['时的科技', 'E20', '电动垂直起降', '适航', '低空出行'],
    cadenceHours: 24,
  },
  {
    id: 'dji-enterprise',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '大疆行业应用',
    url: 'https://enterprise.dji.com/cn',
    crawlMode: 'watch-page',
    keywords: ['行业无人机', '农业无人机', '巡检', '测绘', '应急', '低空'],
    cadenceHours: 24,
  },
  {
    id: 'meituan-drone',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '美团无人机',
    url: 'https://www.meituan.com/',
    crawlMode: 'watch-page',
    keywords: ['美团无人机', '无人机配送', '低空物流', '即时配送', '航线'],
    cadenceHours: 24,
  },
  {
    id: 'sf-uav',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '丰翼科技',
    url: 'https://www.sf-express.com/',
    crawlMode: 'watch-page',
    keywords: ['丰翼', '无人机物流', '低空物流', '顺丰无人机', '配送'],
    cadenceHours: 24,
  },
  {
    id: 'antwork',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '迅蚁科技',
    url: 'https://www.antwork.link/',
    crawlMode: 'watch-page',
    keywords: ['迅蚁', '医疗配送', '无人机物流', '城市配送', '低空物流'],
    cadenceHours: 24,
  },
  {
    id: 'citic-cohc',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '中信海直',
    url: 'https://www.cohc.citic/',
    crawlMode: 'watch-page',
    keywords: ['中信海直', '通航', '直升机', '低空经济', '应急救援'],
    cadenceHours: 24,
  },
  {
    id: 'les-cn',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '莱斯信息',
    url: 'https://www.les.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空', '空管', '飞行服务', '监管平台', '空域管理'],
    cadenceHours: 24,
  },
  {
    id: 'catl',
    market: '中国',
    type: '企业公告',
    credibility: '中高',
    name: '宁德时代',
    url: 'https://www.catl.com/',
    crawlMode: 'watch-page',
    keywords: ['电动飞机', '航空', '电池', '凝聚态电池', '低空'],
    cadenceHours: 24,
  },
  {
    id: 'xinhua',
    market: '中国',
    type: '主流媒体',
    credibility: '中高',
    name: '新华网',
    url: 'https://www.news.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '通用航空', '航空产业', '空域'],
    cadenceHours: 12,
  },
  {
    id: 'people',
    market: '中国',
    type: '主流媒体',
    credibility: '中高',
    name: '人民网',
    url: 'http://www.people.com.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '通用航空', '产业发展', '空域'],
    cadenceHours: 12,
  },
  {
    id: 'cctv',
    market: '中国',
    type: '主流媒体',
    credibility: '中高',
    name: '央视网',
    url: 'https://www.cctv.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '通用航空', '航空产业'],
    cadenceHours: 12,
  },
  {
    id: 'sina-finance',
    market: '中国',
    type: '主流媒体',
    credibility: '中',
    name: '新浪财经',
    url: 'https://finance.sina.com.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '电动垂直起降', '飞行汽车', '通用航空'],
    cadenceHours: 6,
  },
  {
    id: 'tencent-news',
    market: '中国',
    type: '主流媒体',
    credibility: '中',
    name: '腾讯新闻',
    url: 'https://news.qq.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '通用航空'],
    cadenceHours: 6,
  },
  {
    id: 'netease-money',
    market: '中国',
    type: '主流媒体',
    credibility: '中',
    name: '网易财经',
    url: 'https://money.163.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '电动垂直起降', '飞行汽车', '通用航空'],
    cadenceHours: 6,
  },
  {
    id: 'yicai',
    market: '中国',
    type: '主流媒体',
    credibility: '中高',
    name: '第一财经',
    url: 'https://www.yicai.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '航空产业', '通用航空'],
    cadenceHours: 6,
  },
  {
    id: 'cls',
    market: '中国',
    type: '主流媒体',
    credibility: '中高',
    name: '财联社',
    url: 'https://www.cls.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '电动垂直起降', '通用航空'],
    cadenceHours: 6,
  },
  {
    id: 'stcn',
    market: '中国',
    type: '主流媒体',
    credibility: '中高',
    name: '证券时报网',
    url: 'https://www.stcn.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '航空装备', '通用航空'],
    cadenceHours: 6,
  },
  {
    id: 'thepaper',
    market: '中国',
    type: '主流媒体',
    credibility: '中',
    name: '澎湃新闻',
    url: 'https://www.thepaper.cn/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '通用航空', '城市空中交通'],
    cadenceHours: 12,
  },
  {
    id: 'jiemian',
    market: '中国',
    type: '主流媒体',
    credibility: '中',
    name: '界面新闻',
    url: 'https://www.jiemian.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '电动垂直起降', '通用航空'],
    cadenceHours: 12,
  },
  {
    id: '36kr',
    market: '中国',
    type: '行业媒体',
    credibility: '中',
    name: '36氪',
    url: 'https://36kr.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '电动垂直起降', '融资'],
    cadenceHours: 12,
  },
  {
    id: 'huxiu',
    market: '中国',
    type: '行业媒体',
    credibility: '中',
    name: '虎嗅',
    url: 'https://www.huxiu.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '电动垂直起降', '创业'],
    cadenceHours: 12,
  },
  {
    id: 'tmtpost',
    market: '中国',
    type: '行业媒体',
    credibility: '中',
    name: '钛媒体',
    url: 'https://www.tmtpost.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '电动垂直起降', '产业'],
    cadenceHours: 12,
  },
  {
    id: 'iyiou',
    market: '中国',
    type: '行业媒体',
    credibility: '中',
    name: '亿欧',
    url: 'https://www.iyiou.com/',
    crawlMode: 'watch-page',
    keywords: ['低空经济', '无人机', '飞行汽车', '电动垂直起降', '产业'],
    cadenceHours: 12,
  },
  {
    id: 'reuters-aerospace',
    market: '全球',
    type: '主流媒体',
    credibility: '中高',
    name: '路透社航空航天频道',
    url: 'https://www.reuters.com/business/aerospace-defense/',
    crawlMode: 'watch-page',
    keywords: ['air taxi', 'drone', 'aviation', 'electric aircraft'],
    cadenceHours: 6,
  },
  {
    id: 'aviation-week',
    market: '全球',
    type: '行业媒体',
    credibility: '中高',
    name: 'Aviation Week 航空周刊',
    url: 'https://aviationweek.com/',
    crawlMode: 'watch-page',
    keywords: ['advanced air mobility', 'electric aircraft', 'uncrewed', 'drone'],
    cadenceHours: 12,
  },
  {
    id: 'evtols-insights',
    market: '全球',
    type: '行业媒体',
    credibility: '中',
    name: 'eVTOL Insights 行业媒体',
    url: 'https://evtolinsights.com/',
    crawlMode: 'watch-page',
    keywords: ['eVTOL', 'vertiport', 'advanced air mobility'],
    cadenceHours: 12,
  },
  {
    id: 'authorized-self-media',
    market: '中国',
    type: '自媒体观察',
    credibility: '待核验',
    name: '授权自媒体与人工录入池',
    url: 'about:manual-intake',
    crawlMode: 'manual-or-api',
    keywords: ['低空经济', '无人机', '电动垂直起降飞行器', '先进空中交通'],
    cadenceHours: 24,
  },
  {
    id: 'wechat-public-accounts',
    market: '中国',
    type: '自媒体观察',
    credibility: '待核验',
    name: '微信公众号授权来源',
    url: 'about:wechat-authorized',
    crawlMode: 'manual-or-api',
    keywords: ['低空经济', '无人机', '电动垂直起降飞行器', '飞行汽车', '通用航空'],
    cadenceHours: 24,
  },
  {
    id: 'xueqiu-manual',
    market: '中国',
    type: '自媒体观察',
    credibility: '待核验',
    name: '雪球低空经济讨论人工源',
    url: 'about:xueqiu-manual',
    crawlMode: 'manual-or-api',
    keywords: ['低空经济', '无人机', '飞行汽车', '电动垂直起降', '产业链'],
    cadenceHours: 24,
  },
  {
    id: 'zhihu-manual',
    market: '中国',
    type: '自媒体观察',
    credibility: '待核验',
    name: '知乎低空经济话题人工源',
    url: 'about:zhihu-manual',
    crawlMode: 'manual-or-api',
    keywords: ['低空经济', '无人机', '飞行汽车', '电动垂直起降', '通用航空'],
    cadenceHours: 24,
  },
];

export const crawlerPolicy = {
  userAgent: 'low-altitude-economy-radar/0.2 (+respectful research crawler)',
  requestDelayMs: 2200,
  timeoutMs: 12000,
  maxItemsPerSource: 8,
  schedule: {
    intervalMinutes: 67,
    jitterMinutes: 11,
    avoidTopOfHour: true,
    note: '约每 1 小时抓取一次；实际执行时间应在 56-78 分钟之间随机抖动，避免整点固定触发。',
  },
  obeyRobotsTxt: true,
  storeFullText: false,
  storeFields: ['title', 'summary', 'date', 'source', 'sourceType', 'credibility', 'url', 'canonicalUrl', 'keywords'],
};
